### ISSUE TITLE
运行 pnpm print 后无输出，如何排查原因呢

### ISSUE THREAD

**Issue by lt-xu** [busiyiworld/web-printer#2]
hi，我做了两次尝试，第一次使用 vitepres 插件，第二次使用阮一峰插件，其他设置都采用默认的设置
运行 pnpm print 后，日志为

Fetching Pages Info...(node:92391) UnhandledPromiseRejectionWarning
(Use `node --trace-warnings ...` to show where the warning was created)
(node:92391) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:92391) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

userData 内容为空，无 pdf 生成。请问原因可能是什么呢？

**Comment by ourongxing** [comment]
其实说的很清楚了，只是我这边没出现报错。你是用的 windows 吗，node 版本是多少？

**Comment by lt-xu** [comment]
是 macos，node 版本 14.18.3

**Comment by ourongxing** [comment]
> 

那你可以试一下 19，因为我用的这个版本。

```bash
pnpm env use --global 19
```

pnpm 也可以管理 node 版本

**Comment by ourongxing** [comment]
我试了 14 也没出现这个问题，有点奇怪，这样我就没法测试修复。

**Comment by lt-xu** [comment]
我切换到 19 后，会报这个错

(node:3214) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Fetching Pages Info...node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: Executable doesn't exist at /Users/bytedance/Library/Caches/ms-playwright/chromium-1033/chrome-mac/Chromium.app/Contents/MacOS/Chromium
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝]

Node.js v19.3.0
 ELIFECYCLE  Command failed with exit code 1.

运行了 `npx playwright install`，问题同样存在

**Comment by ourongxing** [comment]
不清楚，pnpm create 生成的项目吗

**Comment by ourongxing** [comment]
我试了下，直接 node 运行有问题，我反正一直用的 tsx。

**Comment by lt-xu** [comment]
> 不清楚，pnpm create 生成的项目吗

是的，按照 readme 进行操作的 `pnpm create printer@latest`

**Comment by ourongxing** [comment]
问题解决了吗，目前没有其他人反馈无法使用。

**Comment by lt-xu** [comment]
没有解决，我尝试用新版本再试一下，但运行找不到 0.3.0 版本，报错
ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @web-printer/core@^0.3.0
This error happened while installing a direct dependency of /Users/xx/FE/web_printer_try/web-printer-3/web-printer-4/web-printer-5
The latest release of @web-printer/core is "0.2.5".

运行`pnpm view @web-printer/core versions`，得到的版本列表中最高版本是0.2.5
这是为啥呢

**Comment by ourongxing** [comment]
https://www.npmjs.com/package/@web-printer/core
用 npm 源或者 taobao 源。

**Comment by lt-xu** [comment]
用 0.3.0 版本 chrome 就没有这个问题了 感谢
