### ISSUE TITLE
执行 tsx index.ts 报错

### ISSUE THREAD

**Issue by zenoncao** [busiyiworld/web-printer#3]
报错信息：
Fetching Pages Info...node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Protocol error (Browser.setDownloadBehavior): 'Browser.setDownloadBehavior' wasn't found

node: 18.12
chrome: 最新版

**Comment by ourongxing** [comment]
不清楚。我并没有用到 `Browser.setDownloadBehavior`

**Comment by zenoncao** [comment]
Mac 上没有问题
