### ISSUE TITLE
生成的 pdf 中的答案内容是知乎的登录页面

### ISSUE THREAD

**Issue by fedono** [busiyiworld/web-printer#5]
目前安装了 Chrome 浏览器，Chrome 浏览器已经登录了知乎，生成的 PDF 中有的答案是正常的内容，有的答案都是 知乎的登录页面，显示知乎的登录页面
测试爬取的知乎专栏为 https://www.zhihu.com/collection/20328337 

![image](https://user-images.githubusercontent.com/12681297/212465367-ab56b151-927e-4cb9-8612-d149480a2b93.png)

目前看是爬取的目录是重复的，爬取到了整个专栏的数量，但是因为 没有设置 maxPages，导致一直重复爬取的第一页的数据，然后不断重复爬取第一页知道数量达到整个专栏的文章总数量
![image](https://user-images.githubusercontent.com/12681297/212465387-c24afd19-c8bb-4a32-96d4-9da0a1043d19.png)

爬取到后面，出现了知乎的检测

![image](https://user-images.githubusercontent.com/12681297/212465400-79a24deb-4c11-4d97-b15e-8bc9c190d2e7.png)

**Comment by ourongxing** [comment]
用 new Printer().login() 登录，userdata 不同。
